---
# apt (Debian) tasks file for ansible-role-redcloak/

- name: "Install required packages (Debian)"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: "Install package (Debian)"
  ansible.builtin.apt:
    deb: "/root/software/redcloak/{{ package_name }}"
    state: present
  when:
    - '"redcloak" not in ansible_facts.packages'