---
# Assert tasks file for ansible-role-redcloak

- name: "Test if Software URL and Package Information is set correctly"
  ansible.builtin.assert:
    that:
      - software_url is defined
      - software_url is string
      - package_name is defined
      - package_name is string
      - package_version is defined
      - package_version is string
    quiet: yes

- name: "Test if proxy settings are set correctly"
  ansible.builtin.assert:
    that:
      - proxy is defined
      - proxy is boolean
      - proxy_host is defined
      - proxy_host is string
    quiet: yes
  when:
    - proxy is defined

- name: "Test if SecureWorks Server settings are set correctly"
  ansible.builtin.assert:
    that:
      - secureworks_server is defined
      - secureworks_server is string
      - registration_key is defined
      - registration_key is string
    quiet: yes