---
# dnf (RedHat) tasks file for ansible-role-redcloak/

- name: "Install required packages (dnf)"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  when:
    - ansible_facts['distribution_major_version'] <= '8'
    # No redhat-lsb-core package in RHEL9
    # https://access.redhat.com/solutions/6960807

- name: "Install package (dnf)"
  ansible.builtin.dnf:
    name: "/root/software/redcloak/{{ package_name }}"
    state: present
    disable_gpg_check: yes