---
# Install tasks file for ansible-role-redcloak

- name: "Test if install boolean variable is set correctly"
  ansible.builtin.assert:
    that:
      - install is defined
      - install is boolean
    quiet: yes

- name: "Create software directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/software/redcloak/"
    state: directory

- name: "Check if installer package already exist"
  ansible.builtin.stat:
    path: "/root/software/redcloak/{{ package_name }}"
  register: package

- name: "Download installer package from local repository"
  ansible.builtin.get_url:
    url: "{{ software_url }}/{{ package_name }}"
    dest: "/root/software/redcloak/"
    validate_certs: no
    mode: '0770'
  when:
    - not package.stat.exists | bool

- name: "Install Agent package"
  ansible.builtin.include_tasks: "{{ ansible_facts['pkg_mgr'] }}.yaml"

- name: "Register the SecureWorks Agent (RedCloak)"
  ansible.builtin.shell:
    cmd: "./redcloak register --key {{ registration_key }} --server {{ secureworks_server }} --use_proxy"
    chdir: "{{ redcloak }}/bin/"
  environment:
    http_proxy: "{{ proxy_host }}"
    https_proxy: "{{ proxy_host }}"
  when:
    - redcloak is defined

- name: "Register the SecureWorks Agent (Taegis)"
  ansible.builtin.shell:
    cmd: "./taegisctl register --key {{ registration_key }} --server {{ secureworks_server }} --use_proxy"
    chdir: "{{ taegis }}/bin/"
  environment:
    http_proxy: "{{ proxy_host }}"
    https_proxy: "{{ proxy_host }}"
  when:
    - taegis is defined

- name: "Enable the SecureWorks Agent Service"
  ansible.builtin.service:
    name: "{{ secureworks_service }}"
    state: enabled

- name: "Enable the SecureWorks Agent Updater Service (Taegis)"
  ansible.builtin.service:
    name: "{{ secureworks_update }}"
    state: enabled
  when:
    - taegis is defined

- name: "Start the SecureWorks Service (RedCloak)"
  ansible.builtin.shell:
    cmd: "./redcloak start"
    chdir: "{{ redcloak }}/bin/"
  when:
    - redcloak is defined

- name: "Start the SecureWorks Service (Taegis)"
  ansible.builtin.shell:
    cmd: "./taegisctl start"
    chdir: "{{ taegis }}/bin/"
  when:
    - taegis is defined