---
# Lookup tasks file for ansible-role-redcloak

- name: "Check for SecureWorks install directory"
  ansible.builtin.stat:
    path: /opt/secureworks
  register: result
  ignore_errors: true

- name: "Set Facts for SecureWorks install directory"
  ansible.builtin.set_fact:
    secureworks_home: /opt/secureworks
  when:
    - result.stat.exists
    - result.stat.isdir
    - result.failed is false

- name: "Set Facts for Install variable"
  ansible.builtin.set_fact:
    install: true
  when:
    - secureworks_home is not defined

- name: "Check for RedCloak directory, in secureworks_home"
  ansible.builtin.stat:
    path: "{{ secureworks_home }}/redcloak"
  register: result
  ignore_errors: true

- name: "Set Facts for SecureWorks install directory"
  ansible.builtin.set_fact:
    redcloak: "{{ secureworks_home }}/redcloak"
  when:
    - result.stat.exists
    - result.stat.isdir
    - result.failed is false

- name: "Check for Taegis-Agent directory, in secureworks_home"
  ansible.builtin.stat:
    path: "{{ secureworks_home }}/taegis-agent"
  register: result
  ignore_errors: true

- name: "Set Facts for Taegis-Agent install directory"
  ansible.builtin.set_fact:
    redcloak: "{{ secureworks_home }}/taegis-agent"
  when:
    - result.stat.exists
    - result.stat.isdir
    - result.failed is false

#- name: "Check for Managesoft Configuration INI File"
#  ansible.builtin.stat:
#    path: "{{ managesoft_config_dir }}/etc/config.ini"
#  register: result
#  when:
#    - managesoft_config_dir is defined

#- name: "Set Facts for Managesoft Configuration INI File"
#  ansible.builtin.set_fact:
#    config_file: "{{ managesoft_config_dir }}/etc/config.ini"
#  when:
#    - managesoft_config_dir is defined
#    - result.stat.exists
#    - result.failed is false

- name: "Read Version from existing installed version of redcloak"
  ansible.builtin.shell:
    cmd: "./redcloak --check | grep -i 'version:' | head -n 1 | cut -d ':' -f 2"
    chdir: "{{ secureworks_home }}/redcloak/bin/"
  register: result
  when:
    - secureworks_home is defined

- name: "Set Facts for SecureWorks RedCloak Installed Version"
  ansible.builtin.set_fact:
    installed_version: "{{ result.stdout | split(' ') | last }}"
  when:
    - result is defined
    - result.failed is false

#- name: "Set Facts for Upgrade variable"
#  ansible.builtin.set_fact:
#    upgrade: true
#  when:
#    - installed_version is defined
#    - installed_version != package_version
    #- splunk_version != '7'
