---
# Lookup tasks file for ansible-role-redcloak

- name: "Check for SecureWorks Agent install directory"
  ansible.builtin.stat:
    path: /opt/secureworks
  register: result
  ignore_errors: true

- name: "Set Facts for SecureWorks Agent install directory"
  ansible.builtin.set_fact:
    secureworks: /opt/secureworks
  when:
    - result.stat.exists
    - result.stat.isdir
    - not result.failed | bool

- name: "Set Facts for Install variable"
  ansible.builtin.set_fact:
    install: true
  when:
    - secureworks is not defined

- name: "Check for RedCloak directory, in secureworks"
  ansible.builtin.stat:
    path: "{{ secureworks }}/redcloak"
  register: result
  ignore_errors: true
  when:
    - secureworks is defined

- name: "Set Facts for SecureWorks Agent install directory & Service Name (RedCloak)"
  ansible.builtin.set_fact:
    redcloak: "{{ secureworks }}/redcloak"
    secureworks_service: "redcloak"
  when:
    - secureworks is defined
    - result.stat.exists
    - result.stat.isdir
    - not result.failed | bool

- name: "Check for Taegis-Agent directory, in secureworks"
  ansible.builtin.stat:
    path: "{{ secureworks }}/taegis-agent"
  register: result
  ignore_errors: true
  when:
    - secureworks is defined

- name: "Set Facts for SecureWorks Agent install directory & Service Name (Taegis)"
  ansible.builtin.set_fact:
    taegis: "{{ secureworks }}/taegis-agent"
    secureworks_service: "taegis-agent"
  when:
    - secureworks is defined
    - result.stat.exists
    - result.stat.isdir
    - not result.failed | bool

- name: "Read Version from existing installed version (RedCloak)"
  ansible.builtin.shell:
    cmd: "./redcloak --check | grep -i 'version:' | head -n 1 | cut -d ':' -f 2"
    chdir: "{{ redcloak }}/bin/"
  register: result
  when:
    - redcloak is defined

- name: "Set Facts for SecureWorks Agent Installed Version (RedCloak)"
  ansible.builtin.set_fact:
    installed_version: "{{ result.stdout | split(' ') | last }}"
  when:
    - redcloak is defined
    - result is defined
    - not result.failed | bool

- name: "Set Facts for Upgrade to Taegis Agent from RedCloak Agent"
  ansible.builtin.set_fact:
    replace: true
  when:
    - redcloak is defined
    - taegis is not defined
    - '"taegis" in package_name'

- name: "Set Facts for Upgrade variable"
  ansible.builtin.set_fact:
    upgrade: true
  when:
    - replace is not defined
    - installed_version is defined
    - installed_version < package_version