---
# tasks file for ansible-role-redcloak/

#- name: "Include OS-specific variables"
#  include_vars: "{{ ansible_os_family }}.yaml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

#- name: "Install required packages"
#  ansible.builtin.package:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - unzip
#  when: item|string not in ansible_facts.packages

- name: "Create software directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/software/{{ package_name.split('-')[0] }}/"
    state: directory

- name: "Check if installer package already exist"
  ansible.builtin.stat:
    path: "/root/software/{{ package_name.split('-')[0] }}/{{ package_name }}"
  register: package

- name: "Download installer package from local repository"
  ansible.builtin.get_url:
    url: "{{ software_url }}/{{ package_name }}"
    dest: "/root/software/{{ package_name.split('-')[0] }}/"
    validate_certs: no
    mode: '0770'
  when: package.stat.exists != True

- name: "Install package"
  block:
    - name: "Install package (RHEL)"
      ansible.builtin.package:
        name: "/root/software/{{ package_name.split('-')[0] }}/{{ package_name }}"
        state: present
      when:
        - '"redcloak" not in ansible_facts.packages'
        - ansible_os_family == 'RedHat'
    - name: "Install package (Debian)"
      ansible.builtin.apt:
        deb: "/root/software/{{ package_name.split('-')[0] }}/{{ package_name }}"
        state: present
      when:
        - '"redcloak" not in ansible_facts.packages'
        - ansible_os_family == 'Debian'