---
# tasks file for ansible-role-redcloak

- name: "Include OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yaml"

- name: "Test Access to Proxy Server"
  ansible.builtin.uri:
    url: "{{ proxy_host }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]
  when:
    - proxy | bool

- name: "Test Access to SecureWorks Server"
  ansible.builtin.uri:
    url: "https://{{ secureworks_server }}"
    method: GET
    validate_certs: no
    #status_code: [404]
  environment:
    http_proxy: "{{ proxy_host }}"
    https_proxy: "{{ proxy_host }}"