---
# tasks file for ansible-role-redcloak/

- name: "Include OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yaml"

- name: "Test Access to Proxy Server"
  ansible.builtin.uri:
    url: "{{ proxy_protocol }}://{{ proxy_host }}:{{ proxy_port }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]
  when: proxy != False

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when:
    - ansible_facts.packages is not defined

- name: "Create software directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/software/redcloak/"
    state: directory

- name: "Check if installer package already exist"
  ansible.builtin.stat:
    path: "/root/software/redcloak/{{ package_name }}"
  register: package

- name: "Download installer package from local repository"
  ansible.builtin.get_url:
    url: "{{ software_url }}/{{ package_name }}"
    dest: "/root/software/redcloak/"
    validate_certs: no
    mode: '0770'
  when: package.stat.exists != True

- name: "Include tasks from apt playbook"
  ansible.builtin.include_tasks: apt.yaml
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: "Include tasks from yum playbook"
  ansible.builtin.include_tasks: yum.yaml
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] <= '7'

- name: "Include tasks from dnf playbook"
  ansible.builtin.include_tasks: dnf.yaml
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] >= '8'