---
# yum (RedHat) tasks file for ansible-role-redcloak/

- name: "Install required packages (yum)"
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: "Install package (yum)"
  ansible.builtin.yum:
    name: "/root/software/redcloak/{{ package_name }}"
    state: present